# Generated by Django 4.2.6 on 2023-10-29 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"permissions": [("can_view_product_statistics", "Can view product statistics")]},
        ),
    ]
