# Generated by Django 4.2.6 on 2023-10-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/thumbnails/", verbose_name="Thumbnail Image"
            ),
        ),
    ]
